language: csharp
mono:     none
dist:     xenial
dotnet:   2.2

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test ./ExceptionNotification.Core.Tests/ExceptionNotification.Core.Tests.csproj
